on:
  push:
    branches:
      - master

name: Deploy ECS Image and fargate

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      ENV_PREFIX: ''
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - run: aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 492107414874.dkr.ecr.us-east-1.amazonaws.com
      - run: docker build -t test .
      - run: docker image ls
